name: 'Build (Bach)'

description: 'Build a modular Java project with Bach'

inputs:
  bach-version:
    description: 'Version of Bach to use'
    required: true
    default: 'HEAD'

runs:
  using: "composite"
  steps:
    - name: 'Print Java shell version'
      shell: bash
      run: jshell --version
    - name: 'Build with Bach'
      shell: bash
      run: |
        version=$([[ ${{ inputs.bach-version }} = 'HEAD' ]] echo "" || echo "@${{ inputs.bach-version }}")
        jshell https://sormuras.de/bach${version}/help
