name: 'Bach'

description: 'Build a modular Java project with Bach'

inputs:
  bach-action:
    description: 'Bach action to execute, defaults to build'
    required: true
    default: 'build'
  bach-version:
    description: 'Version of Bach to use, defaults to HEAD'
    required: true
    default: 'HEAD'
  project-name:
    description: 'Name of the modular Java project'
    required: false
  project-version:
    description: 'Version of the modular Java project'
    required: false
  working-directory:
    description: 'Working directory, defaults to github.workspace'
    required: true
    default: ${{ github.workspace }}

runs:
  using: 'composite'
  steps:
    - name: 'Print information'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        echo "pwd=$(pwd)"
        echo "inputs.bach-action=${{ inputs.bach-action }}"
        echo "inputs.bach-version=${{ inputs.bach-version }}"
        echo "inputs.project-name=${{ inputs.project-name }}"
        echo "inputs.project-version=${{ inputs.project-version }}"
        echo "inputs.working-directory=${{ inputs.working-directory }}"
        java -version
        jshell --version

    - name: 'Run Bach'
      shell: bash
      working-directory: ${{ inputs.working-directory }}
      run: |
        bach_action=${{ inputs.bach-action }}
        bach_version=$([[ ${{ inputs.bach-version }} == 'HEAD' ]] && echo '' || echo "@${{ inputs.bach-version }}")
        name=$([[ ${{ inputs.project-name }} == '' ]] && echo '' || echo " -R-Dbach.project.name=${{ inputs.project-name }}")
        version=$([[ ${{ inputs.project-version }} == '' ]] && echo '' || echo " -R-Dbach.project.version=${{ inputs.project-version }}")
        command="jshell${name}${version} https://sormuras.de/bach${bach_version}/${bach_action}"
        echo -e "\n\n${command}\n\n"
        ${command}
