name: 'Build (Bach)'

description: 'Build a modular Java project with Bach'

inputs:
  bach-version:
    description: 'Version of Bach to use'
    required: true
    default: '11.9'

defaults:
  run:
    shell: bash --noprofile --norc -e -o pipefail -o xtrace {0}

runs:
  using: "composite"
  steps:
    - run: jshell https://sormuras.de/bach@${{ inputs.bach-version }}/help
