name: 'Build (Bach)'

description: 'Build a modular Java project with Bach'

inputs:
  bach-version:
    description: 'Version of Bach to use'
    required: true
    default: 'HEAD'

runs:
  using: "composite"
  steps:
    - name: 'Print Java shell version'
      shell: bash
      run: jshell --version
    - name: 'Build with Bach'
      if: inputs.bach-version == 'HEAD'
      shell: bash
      run: jshell https://sormuras.de/bach/help
    - name: 'Build with Bach'
      if: inputs.bach-version != 'HEAD'
      shell: bash
      run: jshell https://sormuras.de/bach@${{ inputs.bach-version }}/help
