name: 'Build (Bach)'

description: 'Build a modular Java project with Bach'

inputs:
  bach-version:
    description: 'Version of Bach to use'
    required: true
    default: '11.9'

runs:
  using: "composite"
  steps:
    - name 'Print Java shell version'
      shell: bash
      run: jshell --version
    - name: 'Build with Bach'
      shell: bash
      run: jshell https://sormuras.de/bach@${{ inputs.bach-version }}/help
