name: Test
on: push

jobs:

  test-head:
    runs-on: ubuntu-latest
    steps:
    - uses: sormuras/bach-build@main

  test-11.9:
    runs-on: ubuntu-latest
    steps:
    - uses: sormuras/bach-build@main
      with:
        bach-version: 11.9

  bach-help:
    runs-on: ubuntu-latest
    steps:
      - uses: sormuras/bach/.github/actions/help@master
