name: Test

on: push

jobs:

  test:
    name: '${{ matrix.test }}: Bach ${{ matrix.bach }}, Java ${{ matrix.java }}, ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, macos-latest, windows-latest ]
        java: [ 17, 18 ]
        bach: [ HEAD, main, 17-M8 ]
        test: [ 'bach-HEAD', 'bach-not-initialized' ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - uses: ./
        with:
          working-directory: test/${{ matrix.test }}
          bach-version: ${{ matrix.bach }}
          bach-arguments: build
      - run: java --module-path .bach/out/main/modules --describe-module test
        working-directory: test/${{ matrix.test }}
