name: Test

on: push

jobs:

  test:
    name: 'Java ${{ matrix.java }} on ${{ matrix.os }}'
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest , macos-latest, windows-latest ]
        java: [ 16-ea ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: ${{ matrix.java }}
      - uses: sormuras/bach-build@main
        with:
          bach-version: 16
          bach-action: build
          project-name: Test
          project-version: 47.11-${{ github.sha }}
          project-main-release: 9
          working-directory: .
      - run: java --module-path .bach/workspace/modules --describe-module test
