name: Test
on: push

jobs:

  test-head:
    runs-on: ubuntu-latest
    steps:
      - name: 'Print information'
        run: |
          echo "pwd=$(pwd)"
          java -version
          jshell --version
      - uses: actions/setup-java@v1
        with:
          java-version: 15
      - uses: sormuras/bach-build@main
